name: Terraform Infrastructure Management

on:
  #workflow_dispatch:
  push:
    branches:
      - master   # Trigger on push to main branch
#     paths:
#       - 'IaC/**'  # Trigger when files in IaC folder change
#   pull_request:
#     branches:
#       - main  # Trigger on pull requests to the main branch
#     paths:
#       - 'IaC/**'  # Trigger when files in IaC folder change

env:
  ACTIONS_RUNNER_DEBUG: true
  AWS_REGION: ap-southeast-1
  AWS_ACCOUNT_ID: 905418236735
  #AWS_ECR_REPO: 905418236735.dkr.ecr.eu-north-1.amazonaws.com/ai-competency/chatbot-admin-dashboard

permissions:
  id-token: write
  contents: write
  security-events: write
  actions: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_nextauth_secret: ${{ secrets.NEXTAUTH_SECRET }}
      TF_VAR_db_url: ${{ secrets.DB_URL }}
      TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}
      TF_VAR_jwt_secret_for_verify: ${{ secrets.JWT_SECRET_FOR_VERIFY }}
      TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
      TF_VAR_sender_password: ${{ secrets.SENDER_PASSWORD }}
      TF_VAR_access_key: ${{ secrets.ACCESS_KEY }}
      TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}
      TF_VAR_session_token: ${{ secrets.SESSION_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.8  # Use the required Terraform version

    - name: Configure AWS OIDC Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-oidc-role
        aws-region: ${{ env.AWS_REGION }}      

    # - name: Export Secrets

    #   run: echo "Secrets exported"

    - name: Terraform Init
      run: |
        terraform init

    - name: Terraform Plan
      run: |
        terraform plan

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve
