name: Terraform Infrastructure Management

on:
  #workflow_dispatch:
  push:
    branches:
      - master  # Trigger on push to main branch
#     paths:
#       - 'IaC/**'  # Trigger when files in IaC folder change
#   pull_request:
#     branches:
#       - main  # Trigger on pull requests to the main branch
#     paths:
#       - 'IaC/**'  # Trigger when files in IaC folder change

env:
  ACTIONS_RUNNER_DEBUG: true
  AWS_REGION: ap-southeast-1
  AWS_ACCOUNT_ID: 905418236735
  AWS_ECR_REPO: 905418236735.dkr.ecr.eu-north-1.amazonaws.com/ai-competency/chatbot-admin-dashboard

permissions:
  id-token: write
  contents: write
  security-events: write
  actions: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.8  # Use the required Terraform version

    - name: Configure AWS OIDC Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-oidc-role
        aws-region: ${{ env.AWS_REGION }}      

    - name: Export Secrets
      env:
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        DB_URL: ${{ secrets.DB_URL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
      run: echo "Secrets exported

    - name: Terraform Init
      run: |
        terraform init

    - name: Terraform Plan
      run: |
        terraform plan

    # - name: Terraform Apply
    #   run: |
    #     terraform apply -auto-approve
